import { redirect } from 'next/navigation';
import { Activity, ArrowRight, LockKeyhole, ShieldCheck } from 'lucide-react';
import { ADMIN_EMAIL, ADMIN_PASSWORD, getAdminSession } from '@/app/admin-auth';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { Field, FieldDescription, FieldGroup, FieldLabel } from '@/components/ui/field';
import { Input } from '@/components/ui/input';

export const dynamic = 'force-dynamic';

export default async function AdminLoginPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  if (await getAdminSession()) redirect('/admin');
  const query = await searchParams;
  return <main id="main" className="admin-surface grid min-h-screen bg-[#171717] p-4 lg:grid-cols-[1fr_minmax(420px,560px)]"><section className="hidden flex-col justify-between p-12 text-white lg:flex"><div className="flex items-center gap-3"><span className="relative size-3 rounded-full bg-white after:absolute after:-right-1.5 after:-top-1.5 after:size-1.5 after:rounded-full after:bg-[#CDBB9F]" /><span className="font-heading text-2xl">Raahi operations</span></div><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[.14em] text-white/50">Synthetic service control plane</p><h1 className="mt-5 text-6xl leading-[.94] tracking-[-.04em]">Every application update, in one calm workspace.</h1><p className="mt-6 max-w-xl text-lg text-white/60">Review the queue, publish progress, and preview citizen notifications without connecting to any real government or messaging service.</p></div><p className="text-xs text-white/42">Independent hackathon prototype—not an official government service</p></section><section className="flex items-center justify-center rounded-[1.75rem] bg-background p-5 sm:p-10"><div className="w-full max-w-md"><span className="grid size-12 place-items-center rounded-xl bg-primary text-primary-foreground"><LockKeyhole /></span><p className="mt-7 text-xs font-semibold uppercase tracking-[.12em] text-muted-foreground">Admin access</p><h2 className="mt-2 text-4xl">Open operations</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Use the public synthetic admin credentials below. This account cannot access any live citizen system.</p>{query.error && <Alert variant="destructive" className="mt-5"><AlertTitle>Credentials did not match</AlertTitle><AlertDescription>Use the displayed demo credentials.</AlertDescription></Alert>}<form action="/api/admin/login" method="post" className="mt-7"><FieldGroup><Field><FieldLabel htmlFor="admin-email">Admin email</FieldLabel><Input id="admin-email" name="email" type="email" defaultValue={ADMIN_EMAIL} autoComplete="username" /><FieldDescription>Public hackathon credential</FieldDescription></Field><Field><FieldLabel htmlFor="admin-password">Password</FieldLabel><Input id="admin-password" name="password" type="text" defaultValue={ADMIN_PASSWORD} autoComplete="current-password" className="font-mono" /></Field></FieldGroup><Button type="submit" size="lg" className="mt-7 w-full">Open admin dashboard<ArrowRight data-icon="inline-end" /></Button></form><Alert className="mt-6 bg-secondary/60"><ShieldCheck /><AlertTitle>Simulation boundary</AlertTitle><AlertDescription>DigiLocker, WhatsApp, identity checks, documents, and status processing are mocked.</AlertDescription></Alert><p className="mt-6 flex items-center gap-2 text-xs text-muted-foreground"><Activity className="size-4 text-success" />Safe synthetic environment</p></div></section></main>;
}
