import Link from 'next/link';
import { Activity, BellRing, FileStack, LayoutDashboard, LogOut, Route, ShieldCheck, UsersRound } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';

export function AdminShell({ active, children }: { active: 'overview' | 'applications'; children: React.ReactNode }) {
  const links = [
    { id: 'overview', label: 'Overview', href: '/admin', icon: LayoutDashboard },
    { id: 'applications', label: 'Applications', href: '/admin#applications', icon: FileStack },
    { id: 'citizens', label: 'Citizens', href: '/admin#citizens', icon: UsersRound },
    { id: 'notifications', label: 'Delivery log', href: '/admin#activity', icon: BellRing },
  ] as const;
  return <div className="admin-surface min-h-screen bg-background text-foreground"><aside className="border-b bg-[#171717] text-white lg:fixed lg:inset-y-0 lg:left-0 lg:w-60 lg:border-b-0 lg:border-r lg:border-white/10"><div className="flex h-16 items-center gap-3 border-b border-white/10 px-5"><span className="relative size-3 rounded-full bg-white after:absolute after:-right-1.5 after:-top-1.5 after:size-1.5 after:rounded-full after:bg-[#CDBB9F]" /><div><p className="font-heading text-xl leading-none">Raahi</p><p className="mt-1 text-[10px] font-semibold uppercase tracking-[.14em] text-white/55">Operations</p></div></div><nav aria-label="Admin" className="admin-nav-scroll flex gap-1 overflow-x-auto p-3 lg:flex-col lg:overflow-visible">{links.map(({ id, label, href, icon: Icon }) => { const current = id === active; return <Link key={id} href={href} aria-current={current ? 'page' : undefined} className={cn('flex min-h-11 shrink-0 items-center gap-3 rounded-lg px-3 text-sm font-medium transition-colors lg:w-full', current ? 'bg-white text-black' : 'text-white/68 hover:bg-white/8 hover:text-white')}><Icon className="size-4" />{label}</Link>; })}</nav><div className="hidden px-4 lg:absolute lg:inset-x-0 lg:bottom-4 lg:block"><div className="rounded-xl border border-white/10 bg-white/5 p-3"><div className="flex items-center gap-2 text-xs font-semibold"><ShieldCheck className="size-4" />Demo environment</div><p className="mt-1 text-[11px] leading-5 text-white/55">No live DigiLocker, government, or WhatsApp connection.</p></div></div></aside><div className="lg:pl-60"><header className="sticky top-0 z-20 flex min-h-16 items-center gap-4 border-b bg-card/95 px-4 backdrop-blur-xl sm:px-6"><div className="min-w-0"><p className="truncate text-sm font-semibold">Transport operations</p><p className="text-xs text-muted-foreground">Synthetic application environment</p></div><div className="ml-auto flex items-center gap-2"><span className="hidden items-center gap-2 rounded-full bg-secondary px-3 py-1.5 text-xs font-medium sm:flex"><Activity className="size-3.5 text-success" />Systems simulated</span><Button asChild variant="ghost" size="sm"><Link href="/en"><Route data-icon="inline-start" />Citizen site</Link></Button><form action="/api/admin/logout" method="post"><Button type="submit" variant="ghost" size="icon-sm" aria-label="Sign out of admin"><LogOut /></Button></form></div></header><main id="main" className="p-4 sm:p-6 lg:p-8">{children}</main></div></div>;
}
