import type { Locale } from '@/lib/i18n';

export const accountCopy = {
  en: {
    account: 'Citizen account',
    overview: 'Overview',
    applications: 'My applications',
    profile: 'Profile',
    preferences: 'Comfort & accessibility',
    services: 'Browse services',
    accountHint: 'Synthetic citizen workspace',
    applicationsEyebrow: 'Application centre',
    applicationsTitle: 'Every application, in one place.',
    applicationsBody: 'Resume drafts, open receipts, and understand what happens next without searching across portals.',
    all: 'All',
    drafts: 'Drafts',
    submitted: 'Submitted',
    renewalApplications: 'Licence renewal',
    otherApplications: 'Other transport services',
    noApplications: 'No applications yet. Choose a service to start a safe synthetic journey.',
    profileEyebrow: 'Citizen profile',
    profileTitle: 'Your synthetic profile.',
    profileBody: 'These fictional details prefill every demo journey. Do not enter real personal information.',
    profileSaved: 'Synthetic profile updated.',
    profileError: 'Check the fictional details and try again.',
    fullName: 'Fictional full name',
    email: 'Demo email',
    phone: 'Synthetic mobile number',
    language: 'Preferred language',
    saveProfile: 'Save synthetic profile',
    identity: 'Linked synthetic identity',
    privacy: 'Privacy by design',
    privacyBody: 'Raahi stores only this fictional profile, mock application records, and document metadata. No uploaded file bytes or government identifiers are used.',
    demoOnly: 'Demo data only',
    active: 'Active',
    view: 'Open application',
    resume: 'Resume draft',
    startService: 'Start another service',
  },
  hi: {
    account: 'नागरिक खाता',
    overview: 'सारांश',
    applications: 'मेरे आवेदन',
    profile: 'प्रोफ़ाइल',
    preferences: 'सुविधा और सुलभता',
    services: 'सेवाएँ देखें',
    accountHint: 'काल्पनिक नागरिक कार्यक्षेत्र',
    applicationsEyebrow: 'आवेदन केंद्र',
    applicationsTitle: 'हर आवेदन, एक जगह।',
    applicationsBody: 'अलग-अलग पोर्टल खोजे बिना ड्राफ्ट जारी रखें, रसीद खोलें और अगला कदम समझें।',
    all: 'सभी',
    drafts: 'ड्राफ्ट',
    submitted: 'जमा',
    renewalApplications: 'लाइसेंस नवीनीकरण',
    otherApplications: 'अन्य परिवहन सेवाएँ',
    noApplications: 'अभी कोई आवेदन नहीं है। सुरक्षित काल्पनिक यात्रा शुरू करने के लिए सेवा चुनें।',
    profileEyebrow: 'नागरिक प्रोफ़ाइल',
    profileTitle: 'आपकी काल्पनिक प्रोफ़ाइल।',
    profileBody: 'ये काल्पनिक विवरण हर डेमो यात्रा में पहले से भरे जाते हैं। वास्तविक व्यक्तिगत जानकारी दर्ज न करें।',
    profileSaved: 'काल्पनिक प्रोफ़ाइल अपडेट हुई।',
    profileError: 'काल्पनिक विवरण जाँचकर फिर प्रयास करें।',
    fullName: 'काल्पनिक पूरा नाम',
    email: 'डेमो ईमेल',
    phone: 'काल्पनिक मोबाइल नंबर',
    language: 'पसंदीदा भाषा',
    saveProfile: 'काल्पनिक प्रोफ़ाइल सहेजें',
    identity: 'जुड़ी हुई काल्पनिक पहचान',
    privacy: 'डिज़ाइन से गोपनीयता',
    privacyBody: 'राही केवल यह काल्पनिक प्रोफ़ाइल, मॉक आवेदन रिकॉर्ड और दस्तावेज़ मेटाडेटा रखता है। कोई अपलोड की गई फ़ाइल या सरकारी पहचान उपयोग नहीं होती।',
    demoOnly: 'केवल डेमो डेटा',
    active: 'सक्रिय',
    view: 'आवेदन खोलें',
    resume: 'ड्राफ्ट जारी रखें',
    startService: 'एक और सेवा शुरू करें',
  },
} as const satisfies Record<Locale, Record<string, string>>;

export const footerCopy = {
  en: {
    eyebrow: 'A clearer route through public services',
    title: 'Start informed. Finish without the maze.',
    body: 'Know the requirements, sample fee, time, and next step before you commit—using safe synthetic records throughout.',
    primary: 'Explore services',
    secondary: 'Open my applications',
    services: 'Services',
    account: 'Account',
    build: 'This prototype',
    licence: 'Driving licence',
    vehicle: 'Vehicle services',
    compliance: 'Safety & compliance',
    guides: 'Guides & information',
    applications: 'My applications',
    profile: 'Citizen profile',
    signIn: 'Demo sign in',
    brief: 'Hackathon brief',
    disclosure: 'Independent prototype',
    privacy: 'Synthetic data policy',
    tagline: 'Transport services, without the maze.',
    backToTop: 'Back to top',
    care: 'Designed with care for',
    citizens: 'India’s citizens',
    copyright: '© 2026 Raahi. Independent hackathon prototype.',
  },
  hi: {
    eyebrow: 'सार्वजनिक सेवाओं का स्पष्ट रास्ता',
    title: 'जानकारी से शुरू करें। बिना उलझन पूरा करें।',
    body: 'सुरक्षित काल्पनिक रिकॉर्ड के साथ शुरू करने से पहले आवश्यकताएँ, नमूना शुल्क, समय और अगला कदम जानें।',
    primary: 'सेवाएँ देखें',
    secondary: 'मेरे आवेदन खोलें',
    services: 'सेवाएँ',
    account: 'खाता',
    build: 'यह प्रोटोटाइप',
    licence: 'ड्राइविंग लाइसेंस',
    vehicle: 'वाहन सेवाएँ',
    compliance: 'सुरक्षा और अनुपालन',
    guides: 'मार्गदर्शिका और जानकारी',
    applications: 'मेरे आवेदन',
    profile: 'नागरिक प्रोफ़ाइल',
    signIn: 'डेमो साइन इन',
    brief: 'हैकाथॉन संक्षिप्त',
    disclosure: 'स्वतंत्र प्रोटोटाइप',
    privacy: 'काल्पनिक डेटा नीति',
    tagline: 'परिवहन सेवाएँ, बिना उलझन।',
    backToTop: 'ऊपर जाएँ',
    care: 'सावधानी से डिज़ाइन किया गया',
    citizens: 'भारत के नागरिकों के लिए',
    copyright: '© 2026 राही। स्वतंत्र हैकाथॉन प्रोटोटाइप।',
  },
} as const satisfies Record<Locale, Record<string, string>>;

export const journeyCopy = {
  en: {
    rail: 'Why Raahi is clearer',
    eyebrow: 'Know before you begin',
    title: 'One guided route. Zero hidden handoffs.',
    body: 'Raahi previews the whole journey before sign-in: requirements, sample fee, estimated time, verification, and recovery are visible from the start.',
    ready: 'Journey readiness',
    known: 'Everything explained',
    time: 'Estimated time',
    fee: 'Sample fee',
    steps: 'Clear stages',
    handoffs: 'Hidden handoffs',
    noHandoffs: 'None in demo',
    requirements: 'Requirements first',
    requirementsBody: 'See exactly what is needed before the first form field.',
    draft: 'Resume anywhere',
    draftBody: 'Every completed step is saved to the signed-in synthetic workspace.',
    recovery: 'Recovery built in',
    recoveryBody: 'Errors explain what happened, what stayed saved, and the next safe action.',
    compare: 'Why this improves the journey',
    compareBody: 'Traditional directories make citizens find the right portal before they can understand a task. Raahi starts with the citizen’s goal and keeps context through receipt and status.',
  },
  hi: {
    rail: 'राही अधिक स्पष्ट क्यों है',
    eyebrow: 'शुरू करने से पहले जानें',
    title: 'एक निर्देशित रास्ता। कोई छिपा हस्तांतरण नहीं।',
    body: 'राही साइन इन से पहले पूरी यात्रा दिखाता है: आवश्यकताएँ, नमूना शुल्क, अनुमानित समय, सत्यापन और सुधार शुरुआत से स्पष्ट हैं।',
    ready: 'यात्रा की तैयारी',
    known: 'सब कुछ समझाया गया',
    time: 'अनुमानित समय',
    fee: 'नमूना शुल्क',
    steps: 'स्पष्ट चरण',
    handoffs: 'छिपे हस्तांतरण',
    noHandoffs: 'डेमो में कोई नहीं',
    requirements: 'पहले आवश्यकताएँ',
    requirementsBody: 'पहला फ़ॉर्म भरने से पहले ठीक-ठीक जानें कि क्या चाहिए।',
    draft: 'कहीं से भी जारी रखें',
    draftBody: 'हर पूरा चरण साइन-इन काल्पनिक कार्यक्षेत्र में सहेजा जाता है।',
    recovery: 'सुधार साथ में',
    recoveryBody: 'त्रुटि बताती है क्या हुआ, क्या सहेजा रहा और अगला सुरक्षित कदम क्या है।',
    compare: 'यह यात्रा बेहतर क्यों है',
    compareBody: 'पुरानी निर्देशिकाएँ नागरिक को काम समझने से पहले सही पोर्टल खोजने देती हैं। राही नागरिक के लक्ष्य से शुरू होकर रसीद और स्थिति तक संदर्भ बनाए रखता है।',
  },
} as const satisfies Record<Locale, Record<string, string>>;
