export const locales = ['en', 'hi'] as const;
export type Locale = (typeof locales)[number];

const en = {
  prototype: 'Hackathon prototype—not an official government service', product: 'Licence Renewal Guide', skip: 'Skip to main content', english: 'English', hindi: 'हिन्दी', signIn: 'Sign in with ChatGPT', signOut: 'Sign out', dashboard: 'My renewal',
  heroEyebrow: 'A clearer citizen journey', heroTitle: 'Renew your licence with clarity.', heroBody: 'Understand what you need, complete each step, and track what happens next—all in one calm, mobile-first flow.', heroPrimary: 'Try the renewal demo', heroSecondary: 'How this prototype works', heroNote: 'Secure sign-in. Synthetic data. No government systems contacted.',
  visualKicker: 'One guided journey', visualTitle: 'From eligibility to receipt', visualStep1: 'Check', visualStep2: 'Update', visualStep3: 'Verify', visualStep4: 'Submit', visualStatus: 'Ready for renewal',
  problemEyebrow: 'Why redesign this?', problemTitle: 'Citizens should not have to decode the portal before completing a task.', problemBody: 'The current experience spreads guidance across dense navigation and separate service handoffs. This prototype brings one journey into a single, explainable sequence.',
  improvement1Title: 'Requirements before forms', improvement1Body: 'Know the documents, fee, and demo limitations before entering anything.', improvement2Title: 'Progress that survives', improvement2Body: 'Each completed step is saved so a citizen can safely return.', improvement3Title: 'Plain-language recovery', improvement3Body: 'Errors explain what happened and the next action to take.',
  pathEyebrow: 'The five-minute demo', pathTitle: 'One connected renewal path', path1: 'Confirm eligibility', path2: 'Review details', path3: 'Select document metadata', path4: 'Use the mock OTP', path5: 'Review and pay ₹450 (mock)',
  disclosureTitle: 'Built safely for the hackathon', disclosureBody: 'Identity verification, documents, OTP, payment, and government processing are simulated. The experience never accepts real Aadhaar, PAN, licence, banking, or government API data.', footer: 'A Build What Moves India hackathon prototype.',
  workspaceEyebrow: 'Citizen workspace', workspaceTitle: 'Your synthetic licence is ready to renew', welcome: 'Welcome', licenceLabel: 'Synthetic driving licence', eligible: 'Eligible for renewal', validUntil: 'Valid until', issuedIn: 'Issuing state', vehicleClasses: 'Vehicle classes', holder: 'Licence holder', address: 'Synthetic address', startRenewal: 'Start a fresh renewal', resumeRenewal: 'Resume renewal', viewStatus: 'View status', noApplications: 'No renewal applications yet.', applicationHistory: 'Application history', whatYouNeed: 'What you will need', need1: 'A synthetic address proof filename', need2: 'The visible demo OTP: 123456', need3: 'About five minutes—no real payment details',
  wizardEyebrow: 'Synthetic licence renewal', wizardTitle: 'Renew your driving licence', stepOf: 'Step {current} of {total}', saved: 'Draft saved', saving: 'Saving…', back: 'Back', continue: 'Save and continue', explain: 'Explain this step', step0: 'Eligibility', step1: 'Your details', step2: 'Documents', step3: 'Verification', step4: 'Review', step5: 'Mock payment',
  eligibilityTitle: 'You can continue with this demo renewal', eligibilityBody: 'This synthetic licence is within the prototype renewal window. A real service would verify legal eligibility with the issuing authority.', requirementsTitle: 'Before you continue', requirementA: 'Your existing synthetic licence details', requirementB: 'One address-proof filename (metadata only)', requirementC: 'A ₹450 simulated renewal fee', confirmEligibility: 'I understand this eligibility result is simulated.',
  detailsTitle: 'Confirm how we should contact you', detailsBody: 'These details are synthetic and are only stored for your signed-in demo workspace.', email: 'Email address', phone: 'Mobile number', fullAddress: 'Address',
  documentsTitle: 'Select document metadata', documentsBody: 'Choose a sample file from your device. The prototype stores only its filename and size—no file bytes are uploaded.', documentType: 'Document type', addressProof: 'Address proof', medicalCertificate: 'Medical certificate (optional)', chooseFile: 'Choose a sample file', selectedFile: 'Selected metadata', remove: 'Remove',
  otpTitle: 'Enter the visible demo OTP', otpBody: 'No SMS is sent. Use this mock code to test the verification step.', demoCode: 'Demo code: 123456', otp: 'Six-digit OTP',
  reviewTitle: 'Review every change', reviewBody: 'Confirm the synthetic contact details, document metadata, and renewal fee before submission.', declaration1: 'I confirm that all information in this prototype is synthetic.', declaration2: 'I understand this does not submit a renewal to any government authority.',
  paymentTitle: 'Simulate the ₹450 payment', paymentBody: 'No card, bank, or UPI details are collected. Continue to generate a mock transaction reference and receipt.', amount: 'Renewal fee', paymentMethod: 'Method', mockGateway: 'Mock payment gateway', submitPayment: 'Simulate payment and submit',
  errorGeneric: 'Something went wrong. Your saved steps are unchanged. Please try again.', errorEligibility: 'Confirm the simulated eligibility result to continue.', errorDocument: 'Select one sample address-proof file to continue.', errorOtp: 'Enter the demo code 123456.', errorDeclarations: 'Accept both declarations to continue.',
  assistantTitle: 'Step explainer', assistantLimits: 'This helper explains the prototype only. It cannot determine legal eligibility, access government systems, or submit forms.', assistantQuestion: 'What would you like explained?', assistantPlaceholder: 'For example: Why is this document needed?', assistantSend: 'Ask helper', assistantFallback: 'Showing the built-in guide because the AI service is unavailable.', assistantPrivacy: 'Do not enter names, licence numbers, document contents, phone numbers, or addresses.', close: 'Close',
  receiptEyebrow: 'Mock submission complete', receiptTitle: 'Your synthetic renewal was submitted', receiptBody: 'Keep this mock reference for the demo. No government application or payment was created.', applicationNumber: 'Application reference', transactionNumber: 'Mock transaction reference', submittedOn: 'Submitted on', downloadReceipt: 'Print mock receipt', trackTitle: 'What happens next', submitted: 'Submitted', documentsChecking: 'Documents checking', underReview: 'Under review', approved: 'Approved', actionRequired: 'Action required', current: 'Current', upcoming: 'Upcoming', completed: 'Completed', statusSubmittedBody: 'Your synthetic application and mock payment are recorded.', statusDocumentsBody: 'Document metadata would be checked for completeness.', statusReviewBody: 'The issuing authority would review the renewal request.', statusApprovedBody: 'A renewed licence would be issued after approval.', expected: 'Expected demo timing', expectedValue: '2–4 simulated working days', returnDashboard: 'Return to dashboard',
} as const;

type CopyKey = keyof typeof en;

const hi: Record<CopyKey, string> = {
  prototype: 'हैकाथॉन प्रोटोटाइप—यह आधिकारिक सरकारी सेवा नहीं है', product: 'लाइसेंस नवीनीकरण मार्गदर्शिका', skip: 'मुख्य सामग्री पर जाएँ', english: 'English', hindi: 'हिन्दी', signIn: 'ChatGPT से साइन इन करें', signOut: 'साइन आउट', dashboard: 'मेरा नवीनीकरण',
  heroEyebrow: 'नागरिकों के लिए स्पष्ट प्रक्रिया', heroTitle: 'अपना लाइसेंस आसानी से नवीनीकृत करें।', heroBody: 'ज़रूरतों को समझें, हर चरण पूरा करें और आगे की स्थिति देखें—एक सरल, मोबाइल-फर्स्ट अनुभव में।', heroPrimary: 'नवीनीकरण डेमो आज़माएँ', heroSecondary: 'यह प्रोटोटाइप कैसे काम करता है', heroNote: 'सुरक्षित साइन-इन। काल्पनिक डेटा। किसी सरकारी सिस्टम से संपर्क नहीं।',
  visualKicker: 'एक निर्देशित प्रक्रिया', visualTitle: 'पात्रता से रसीद तक', visualStep1: 'जाँच', visualStep2: 'अपडेट', visualStep3: 'सत्यापन', visualStep4: 'जमा', visualStatus: 'नवीनीकरण के लिए तैयार',
  problemEyebrow: 'इसे नया क्यों बनाएँ?', problemTitle: 'किसी कार्य को पूरा करने से पहले नागरिक को पोर्टल समझने की ज़रूरत नहीं होनी चाहिए।', problemBody: 'मौजूदा अनुभव में जानकारी घने नेविगेशन और अलग-अलग सेवाओं में बँटी है। यह प्रोटोटाइप एक काम को एक स्पष्ट क्रम में लाता है।',
  improvement1Title: 'फ़ॉर्म से पहले आवश्यकताएँ', improvement1Body: 'कुछ भी भरने से पहले दस्तावेज़, शुल्क और डेमो की सीमाएँ जानें।', improvement2Title: 'सुरक्षित प्रगति', improvement2Body: 'हर पूरा चरण सहेजा जाता है ताकि आप बाद में लौट सकें।', improvement3Title: 'सरल समाधान', improvement3Body: 'त्रुटि संदेश कारण और अगला कदम दोनों बताता है।',
  pathEyebrow: 'पाँच मिनट का डेमो', pathTitle: 'एक जुड़ी हुई नवीनीकरण प्रक्रिया', path1: 'पात्रता की पुष्टि', path2: 'विवरण की जाँच', path3: 'दस्तावेज़ मेटाडेटा चुनें', path4: 'मॉक OTP का उपयोग', path5: 'जाँचें और ₹450 भुगतान करें (मॉक)',
  disclosureTitle: 'हैकाथॉन के लिए सुरक्षित रूप से बनाया गया', disclosureBody: 'पहचान सत्यापन, दस्तावेज़, OTP, भुगतान और सरकारी प्रक्रिया सभी सिम्युलेटेड हैं। यहाँ वास्तविक आधार, पैन, लाइसेंस, बैंकिंग या सरकारी API डेटा स्वीकार नहीं किया जाता।', footer: 'Build What Moves India हैकाथॉन प्रोटोटाइप।',
  workspaceEyebrow: 'नागरिक कार्यक्षेत्र', workspaceTitle: 'आपका काल्पनिक लाइसेंस नवीनीकरण के लिए तैयार है', welcome: 'स्वागत है', licenceLabel: 'काल्पनिक ड्राइविंग लाइसेंस', eligible: 'नवीनीकरण के लिए पात्र', validUntil: 'मान्य तिथि', issuedIn: 'जारी करने वाला राज्य', vehicleClasses: 'वाहन श्रेणियाँ', holder: 'लाइसेंस धारक', address: 'काल्पनिक पता', startRenewal: 'नया नवीनीकरण शुरू करें', resumeRenewal: 'नवीनीकरण जारी रखें', viewStatus: 'स्थिति देखें', noApplications: 'अभी कोई नवीनीकरण आवेदन नहीं है।', applicationHistory: 'आवेदन इतिहास', whatYouNeed: 'आपको क्या चाहिए', need1: 'एक काल्पनिक पते के प्रमाण की फ़ाइल का नाम', need2: 'दिखाई देने वाला डेमो OTP: 123456', need3: 'लगभग पाँच मिनट—कोई वास्तविक भुगतान विवरण नहीं',
  wizardEyebrow: 'काल्पनिक लाइसेंस नवीनीकरण', wizardTitle: 'अपना ड्राइविंग लाइसेंस नवीनीकृत करें', stepOf: 'चरण {current}, कुल {total}', saved: 'ड्राफ्ट सहेजा गया', saving: 'सहेज रहे हैं…', back: 'पीछे', continue: 'सहेजें और आगे बढ़ें', explain: 'इस चरण को समझें', step0: 'पात्रता', step1: 'आपका विवरण', step2: 'दस्तावेज़', step3: 'सत्यापन', step4: 'जाँच', step5: 'मॉक भुगतान',
  eligibilityTitle: 'आप इस डेमो नवीनीकरण को जारी रख सकते हैं', eligibilityBody: 'यह काल्पनिक लाइसेंस प्रोटोटाइप की नवीनीकरण अवधि में है। वास्तविक सेवा कानूनी पात्रता जारी करने वाले प्राधिकरण से जाँचेगी।', requirementsTitle: 'आगे बढ़ने से पहले', requirementA: 'आपके मौजूदा काल्पनिक लाइसेंस का विवरण', requirementB: 'पते के प्रमाण की एक फ़ाइल का नाम (केवल मेटाडेटा)', requirementC: '₹450 का सिम्युलेटेड शुल्क', confirmEligibility: 'मैं समझता/समझती हूँ कि यह पात्रता परिणाम सिम्युलेटेड है।',
  detailsTitle: 'संपर्क विवरण की पुष्टि करें', detailsBody: 'ये विवरण काल्पनिक हैं और केवल आपके साइन-इन डेमो कार्यक्षेत्र में सहेजे जाते हैं।', email: 'ईमेल पता', phone: 'मोबाइल नंबर', fullAddress: 'पता', documentsTitle: 'दस्तावेज़ मेटाडेटा चुनें', documentsBody: 'अपने डिवाइस से एक नमूना फ़ाइल चुनें। केवल नाम और आकार सहेजा जाएगा—फ़ाइल अपलोड नहीं होगी।', documentType: 'दस्तावेज़ का प्रकार', addressProof: 'पते का प्रमाण', medicalCertificate: 'मेडिकल प्रमाणपत्र (वैकल्पिक)', chooseFile: 'नमूना फ़ाइल चुनें', selectedFile: 'चुना गया मेटाडेटा', remove: 'हटाएँ',
  otpTitle: 'दिखाई देने वाला डेमो OTP दर्ज करें', otpBody: 'कोई SMS नहीं भेजा जाता। सत्यापन चरण के लिए इस मॉक कोड का उपयोग करें।', demoCode: 'डेमो कोड: 123456', otp: 'छह अंकों का OTP', reviewTitle: 'हर बदलाव की जाँच करें', reviewBody: 'जमा करने से पहले काल्पनिक संपर्क विवरण, दस्तावेज़ मेटाडेटा और शुल्क की पुष्टि करें।', declaration1: 'मैं पुष्टि करता/करती हूँ कि इस प्रोटोटाइप की सारी जानकारी काल्पनिक है।', declaration2: 'मैं समझता/समझती हूँ कि इससे किसी सरकारी प्राधिकरण को आवेदन जमा नहीं होता।', paymentTitle: '₹450 भुगतान सिम्युलेट करें', paymentBody: 'कार्ड, बैंक या UPI विवरण नहीं लिए जाते। मॉक संदर्भ और रसीद बनाने के लिए आगे बढ़ें।', amount: 'नवीनीकरण शुल्क', paymentMethod: 'तरीका', mockGateway: 'मॉक भुगतान गेटवे', submitPayment: 'भुगतान सिम्युलेट कर जमा करें',
  errorGeneric: 'कुछ गलत हुआ। सहेजे गए चरण सुरक्षित हैं। कृपया फिर कोशिश करें।', errorEligibility: 'आगे बढ़ने के लिए सिम्युलेटेड पात्रता की पुष्टि करें।', errorDocument: 'आगे बढ़ने के लिए पते के प्रमाण की एक नमूना फ़ाइल चुनें।', errorOtp: 'डेमो कोड 123456 दर्ज करें।', errorDeclarations: 'आगे बढ़ने के लिए दोनों घोषणाएँ स्वीकार करें।',
  assistantTitle: 'चरण सहायक', assistantLimits: 'यह सहायक केवल प्रोटोटाइप समझाता है। यह कानूनी पात्रता तय नहीं कर सकता, सरकारी सिस्टम नहीं खोल सकता और फ़ॉर्म जमा नहीं कर सकता।', assistantQuestion: 'आप क्या समझना चाहते हैं?', assistantPlaceholder: 'उदाहरण: इस दस्तावेज़ की ज़रूरत क्यों है?', assistantSend: 'सहायक से पूछें', assistantFallback: 'AI सेवा उपलब्ध नहीं है, इसलिए अंतर्निहित मार्गदर्शिका दिखाई जा रही है।', assistantPrivacy: 'नाम, लाइसेंस नंबर, दस्तावेज़ सामग्री, फोन नंबर या पता दर्ज न करें।', close: 'बंद करें',
  receiptEyebrow: 'मॉक आवेदन पूरा', receiptTitle: 'आपका काल्पनिक नवीनीकरण जमा हो गया', receiptBody: 'डेमो के लिए यह मॉक संदर्भ रखें। कोई सरकारी आवेदन या भुगतान नहीं बनाया गया।', applicationNumber: 'आवेदन संदर्भ', transactionNumber: 'मॉक लेनदेन संदर्भ', submittedOn: 'जमा करने की तारीख', downloadReceipt: 'मॉक रसीद प्रिंट करें', trackTitle: 'अब आगे क्या होगा', submitted: 'जमा', documentsChecking: 'दस्तावेज़ जाँच', underReview: 'समीक्षा में', approved: 'स्वीकृत', actionRequired: 'कार्रवाई आवश्यक', current: 'वर्तमान', upcoming: 'आगामी', completed: 'पूरा', statusSubmittedBody: 'आपका काल्पनिक आवेदन और मॉक भुगतान दर्ज है।', statusDocumentsBody: 'दस्तावेज़ मेटाडेटा की पूर्णता जाँची जाएगी।', statusReviewBody: 'जारी करने वाला प्राधिकरण नवीनीकरण अनुरोध की समीक्षा करेगा।', statusApprovedBody: 'स्वीकृति के बाद नवीनीकृत लाइसेंस जारी होगा।', expected: 'अनुमानित डेमो समय', expectedValue: '2–4 सिम्युलेटेड कार्यदिवस', returnDashboard: 'डैशबोर्ड पर लौटें',
};

export type Copy = Record<CopyKey, string>;
export function isLocale(value: string): value is Locale { return locales.includes(value as Locale); }
export function getCopy(locale: Locale): Copy { return locale === 'hi' ? hi : en; }
export function localPath(locale: Locale, path = '') { return `/${locale}${path.startsWith('/') ? path : `/${path}`}`.replace(/\/$/, '') || `/${locale}`; }
