import type { Locale } from '@/lib/i18n';

const en = {
  eyebrow: 'Renewal readiness',
  title: 'Know what you need before you begin.',
  body: 'Describe your situation or answer six simple questions. Raahi will prepare a synthetic checklist without asking for a licence number.',
  copilotTitle: 'Tell Raahi what you need',
  copilotBody: 'Use English, Hindi, or Hinglish. Do not enter a real name, licence number, phone number, or address.',
  copilotPlaceholder: 'For example: I am 55, my private licence expires next month, and I live in Delhi.',
  samplePrompt: 'I am 55, my private licence expires next month, and I live in Delhi.',
  interpret: 'Understand my situation',
  listening: 'Listening…',
  startVoice: 'Speak instead',
  stopVoice: 'Stop listening',
  voiceUnavailable: 'Voice input is not available in this browser. You can type the same request.',
  assistantFallback: 'Built-in language guide used',
  assistantAi: 'AI-assisted interpretation',
  understood: 'What Raahi understood',
  editable: 'Every answer remains editable. The rules—not AI—create the checklist.',
  assessmentTitle: 'Confirm these details',
  age: 'Age range',
  ageUnder40: '18–39 years',
  age4059: '40–59 years',
  age60: '60 years or above',
  licenceType: 'Licence type',
  private: 'Private vehicle',
  transport: 'Transport or commercial',
  expiry: 'When does the licence expire?',
  expiryFar: 'More than one year away',
  expirySoon: 'Within the next year',
  expiredRecent: 'Expired less than one year ago',
  expiredLate: 'Expired more than one year ago',
  state: 'Issuing state for this demo',
  addressChanged: 'My address also changed',
  route: 'How would you prefer to complete it?',
  standard: 'Online self-service',
  assisted: 'Assisted-centre guidance',
  showPlan: 'Show my readiness plan',
  resultEyebrow: 'Your prepared plan',
  readyTitle: 'You are ready to begin this synthetic renewal.',
  attentionTitle: 'You can continue, but review these possible blockers.',
  resultBody: 'This is an explainable prototype result—not a legal eligibility decision.',
  readyNow: 'Ready now',
  documents: 'Prepare these items',
  blockers: 'Check before continuing',
  noBlockers: 'No additional blockers were identified for this synthetic scenario.',
  medical: 'Medical form',
  visit: 'Illustrative office visit',
  required: 'Likely required in this prototype',
  notRequired: 'Not identified for this scenario',
  expected: 'Estimated demo time',
  minutes: 'minutes',
  fee: 'Sample fee',
  sources: 'Sources and limits',
  sourceBody: 'Raahi uses a small versioned demonstration rule set based on public official guidance. Requirements can vary and a real authority would make the final decision.',
  why: 'Why?',
  start: 'Start prepared renewal',
  signIn: 'Sign in to start this prepared renewal',
  change: 'Change answers',
  savedLocal: 'Your answers are saved on this device until you sign in.',
  mockNotice: 'Synthetic assessment only. No government system is contacted.',
  compareTitle: 'What Raahi changes',
  compareBody: 'A prototype comparison of visible journey behavior—not official performance data.',
  dimension: 'Journey behavior',
  current: 'Typical current-style journey',
  raahi: 'Raahi prototype',
  comparison: [
    ['Portal handoffs', 'Multiple destinations', 'One guided journey'],
    ['Requirements before starting', 'Often discovered later', 'Shown up front'],
    ['Interrupted application', 'Recovery may be unclear', 'Draft stays safe'],
    ['Language continuity', 'Can change between pages', 'Preserved throughout'],
    ['After submission', 'Status label', 'Next action explained'],
  ],
} as const;

const hi = {
  eyebrow: 'नवीनीकरण की तैयारी',
  title: 'शुरू करने से पहले जानें कि आपको क्या चाहिए।',
  body: 'अपनी स्थिति बताएँ या छह आसान प्रश्नों के उत्तर दें। Raahi लाइसेंस नंबर माँगे बिना एक काल्पनिक चेकलिस्ट तैयार करेगा।',
  copilotTitle: 'Raahi को बताएँ कि आपको क्या करना है',
  copilotBody: 'हिन्दी, अंग्रेज़ी या हिंग्लिश में लिखें। वास्तविक नाम, लाइसेंस नंबर, फोन नंबर या पता दर्ज न करें।',
  copilotPlaceholder: 'उदाहरण: मेरी उम्र 55 है, निजी लाइसेंस अगले महीने समाप्त होगा और मैं दिल्ली में रहता हूँ।',
  samplePrompt: 'मेरी उम्र 55 है, निजी लाइसेंस अगले महीने समाप्त होगा और मैं दिल्ली में रहता हूँ।',
  interpret: 'मेरी स्थिति समझें',
  listening: 'सुन रहे हैं…',
  startVoice: 'बोलकर बताएँ',
  stopVoice: 'सुनना बंद करें',
  voiceUnavailable: 'इस ब्राउज़र में आवाज़ इनपुट उपलब्ध नहीं है। आप वही बात लिख सकते हैं।',
  assistantFallback: 'अंतर्निहित भाषा मार्गदर्शिका उपयोग हुई',
  assistantAi: 'AI की सहायता से समझा गया',
  understood: 'Raahi ने क्या समझा',
  editable: 'हर उत्तर बदला जा सकता है। चेकलिस्ट नियम बनाते हैं—AI नहीं।',
  assessmentTitle: 'इन विवरणों की पुष्टि करें',
  age: 'आयु वर्ग',
  ageUnder40: '18–39 वर्ष',
  age4059: '40–59 वर्ष',
  age60: '60 वर्ष या अधिक',
  licenceType: 'लाइसेंस का प्रकार',
  private: 'निजी वाहन',
  transport: 'परिवहन या व्यावसायिक',
  expiry: 'लाइसेंस कब समाप्त होता है?',
  expiryFar: 'एक वर्ष से अधिक समय बाद',
  expirySoon: 'अगले एक वर्ष में',
  expiredRecent: 'एक वर्ष से कम समय पहले समाप्त',
  expiredLate: 'एक वर्ष से अधिक समय पहले समाप्त',
  state: 'इस डेमो के लिए जारी करने वाला राज्य',
  addressChanged: 'मेरा पता भी बदल गया है',
  route: 'आप इसे कैसे पूरा करना चाहेंगे?',
  standard: 'ऑनलाइन स्वयं सेवा',
  assisted: 'सहायता केंद्र मार्गदर्शन',
  showPlan: 'मेरी तैयारी योजना दिखाएँ',
  resultEyebrow: 'आपकी तैयार योजना',
  readyTitle: 'आप यह काल्पनिक नवीनीकरण शुरू करने के लिए तैयार हैं।',
  attentionTitle: 'आप आगे बढ़ सकते हैं, लेकिन इन संभावित बाधाओं को जाँचें।',
  resultBody: 'यह समझाया जा सकने वाला प्रोटोटाइप परिणाम है—कानूनी पात्रता का निर्णय नहीं।',
  readyNow: 'अभी तैयार',
  documents: 'इन चीज़ों को तैयार रखें',
  blockers: 'आगे बढ़ने से पहले जाँचें',
  noBlockers: 'इस काल्पनिक स्थिति में कोई अतिरिक्त बाधा नहीं मिली।',
  medical: 'मेडिकल फॉर्म',
  visit: 'उदाहरण कार्यालय यात्रा',
  required: 'इस प्रोटोटाइप में संभवतः आवश्यक',
  notRequired: 'इस स्थिति में आवश्यक नहीं मिला',
  expected: 'अनुमानित डेमो समय',
  minutes: 'मिनट',
  fee: 'नमूना शुल्क',
  sources: 'स्रोत और सीमाएँ',
  sourceBody: 'Raahi सार्वजनिक आधिकारिक मार्गदर्शन पर आधारित छोटे, संस्करणयुक्त डेमो नियमों का उपयोग करता है। आवश्यकताएँ बदल सकती हैं और अंतिम निर्णय वास्तविक प्राधिकरण करेगा।',
  why: 'क्यों?',
  start: 'तैयार नवीनीकरण शुरू करें',
  signIn: 'तैयार नवीनीकरण शुरू करने के लिए साइन इन करें',
  change: 'उत्तर बदलें',
  savedLocal: 'साइन इन करने तक आपके उत्तर इसी डिवाइस पर सहेजे गए हैं।',
  mockNotice: 'केवल काल्पनिक मूल्यांकन। किसी सरकारी सिस्टम से संपर्क नहीं होता।',
  compareTitle: 'Raahi क्या बदलता है',
  compareBody: 'दिखाई देने वाली प्रक्रिया का प्रोटोटाइप तुलना—आधिकारिक प्रदर्शन डेटा नहीं।',
  dimension: 'प्रक्रिया का व्यवहार',
  current: 'सामान्य मौजूदा प्रक्रिया',
  raahi: 'Raahi प्रोटोटाइप',
  comparison: [
    ['पोर्टल के बीच जाना', 'कई अलग स्थान', 'एक निर्देशित प्रक्रिया'],
    ['शुरू करने से पहले आवश्यकताएँ', 'अक्सर बाद में पता चलती हैं', 'पहले ही दिखाई जाती हैं'],
    ['प्रक्रिया रुकने पर', 'वापसी अस्पष्ट हो सकती है', 'ड्राफ्ट सुरक्षित रहता है'],
    ['भाषा की निरंतरता', 'पृष्ठों के बीच बदल सकती है', 'पूरी प्रक्रिया में बनी रहती है'],
    ['जमा करने के बाद', 'सिर्फ स्थिति लेबल', 'अगला कदम समझाया जाता है'],
  ],
} as const;

export const readinessCopy = { en, hi } as const satisfies Record<Locale, object>;
export type ReadinessCopy = (typeof readinessCopy)[Locale];
